Footer
HackBeanpot/www-2019 pull request #149
Opened 2020-07-31 03:11 UTC by catuberretta

Footer! I did have to add a no outline for the hover: focus...unsure why this doesn't happen for other buttons on the site given they need the extra css

2020-07-31 15:48 UTC, daniaalnahdi commented on src/components/footer.jsx
> +import addToMailchimp from 'gatsby-plugin-mailchimp';
nitpick: move the mailchimp import upwards so it's lined up with the rest of the packages (maybe right under import React)

2020-07-31 15:48 UTC, daniaalnahdi commented on src/components/footer.jsx
> +    console.log(e.target.value) //for testing
we can delete this for now since we know it works :)

2020-07-31 15:49 UTC, daniaalnahdi commented on src/components/footer.jsx
> +    console.log(e.target.value) //for testing
same comment on deleting console.log statement above

2020-07-31 15:50 UTC, daniaalnahdi commented on src/components/footer.jsx
> +  const handleSubmit = (e) => {
we don't need to pass in "e" here since we don't need it

2020-07-31 15:52 UTC, daniaalnahdi commented on src/components/footer.jsx
> +      console.log(data)
instead of logging the data, maybe we can display it to the user as a success message? (ping me and I can help!)

2020-07-31 15:52 UTC, daniaalnahdi commented on src/components/footer.jsx
> +      // returns a 200 status code
same comment above about rendering an alert message

2020-07-31 15:52 UTC, daniaalnahdi commented on src/components/footer.jsx
> +      console.log(data)
or even change the button temporarily to "subscribed!"

2020-07-31 15:55 UTC, daniaalnahdi commented on src/components/footer.jsx
> +  export default Footer;
just a reminder to run `npm run format` to get rid of any spacing/clean up the code :)

2020-07-31 15:58 UTC, daniaalnahdi requested changes
just a couple of comments on code clean up + a suggestion on handling success and error messages

2020-07-31 20:52 UTC, daniaalnahdi commented on src/components/footer.jsx
> +  const handleSubmit = (e) => {
wait NVM... just realized that you use this to call e.preventDefault() at the end of the function, which should be the first thing you call

2020-07-31 20:52 UTC, daniaalnahdi commented on src/components/footer.jsx
> +   e.preventDefault();
you should call this at the very start of the function

2020-09-20 01:28 UTC, snwessel approved these changes
This looks so great! @catuberretta and @daniaalnahdi thank you for all of your work on this! Also, the messages like "you've already subscribed" were a really nice touch 😀

2020-09-21 21:41 UTC, daniaalnahdi approved these changes

2020-10-05 15:02 UTC, merged